import xwaf.utils.configs as config_utils


def options(ctx):
    ctx.add_option('--config', action='store', default='')


def configure(conf):
    def make_config(name, flags):
        conf.setenv(name)
        conf.load('xwaf.compiler_xcc')
        conf.env.XCC_FLAGS = flags

    for key, value in CONFIGS.iteritems():
        make_config(key, value)


def build(bld):
    if not config_utils.check_build_config(bld, CONFIGS):
        return

    bld.env.PROJECT_ROOT = '../../..'

    depends_on = ['lib_ethernet']

    if 'mii_25Mhz' in bld.cmd:
        bld.env.TARGET_ARCH = 'STARTKIT'
    elif 'rgmii_25Mhz' in bld.cmd:
        bld.env.TARGET_ARCH = 'XCORE-200-EXPLORER'
    elif 'rgmii_125Mhz' in bld.cmd:
        bld.env.TARGET_ARCH = 'XCORE-200-EXPLORER'
    else:
        bld.env.TARGET_ARCH = 'XK-1A'

    includes = ['../include']

    prog = bld.program(depends_on=depends_on, includes=includes)


common_flags = [
    '-g', '-report', '-DDEBUG_PRINT_ENABLE', '-save-temps', '-Os', '-Xmapper',
    '--map', '-Xmapper', 'MAPFILE', '-DETHERNET_SUPPORT_TRAFFIC_SHAPER=1'
]

CONFIGS = {
    'mii_25Mhz':
    common_flags +
    ['-DRT=1', '-DRGMII=0', '-DETHERNET_SUPPORT_HP_QUEUES=1', '-DCLK_125=0'],
    'rgmii_25Mhz':
    common_flags + [
        '-DRT=0', '-DRGMII=1', '-DETHERNET_SUPPORT_HP_QUEUES=1', '-DCLK_125=0',
        '-fno-xta-info'
    ],
    'rgmii_125Mhz':
    common_flags + [
        '-DRT=0', '-DRGMII=1', '-DETHERNET_SUPPORT_HP_QUEUES=1', '-DCLK_125=1',
        '-fno-xta-info'
    ]
}

config_utils.register_configs(CONFIGS)
