// Copyright 2025 XMOS LIMITED.
// This Software is subject to the terms of the XMOS Public Licence: Version 1.
#ifndef __XSCOPE_CONTROL_H__
#define __XSCOPE_CONTROL_H__

#include <xs1.h>
#include <xscope_cmds_enum.h> // Autogenerated. See CMakeLists.txt

void xscope_control(chanend c_xscope, chanend c_clients[num_clients], static const unsigned num_clients);

#endif
