#ifdef __ethernet_conf_exists__
#include "ethernet_conf.h"
#endif

#ifndef ETHERNET_RX_HP_QUEUE
#define ETHERNET_RX_HP_QUEUE (0)
#endif

#ifndef ETHERNET_TX_HP_QUEUE
#define ETHERNET_TX_HP_QUEUE (0)
#endif

#ifndef ETHERNET_TRAFFIC_SHAPER
#define ETHERNET_TRAFFIC_SHAPER (0)
#endif

#define MII_CREDIT_FRACTIONAL_BITS 16

#ifndef ETHERNET_RX_BUFSIZE_LOW_PRIORITY
#ifdef ETHERNET_RX_BUFSIZE
#define ETHERNET_RX_BUFSIZE_LOW_PRIORITY ETHERNET_RX_BUFSIZE
#else
#define ETHERNET_RX_BUFSIZE_LOW_PRIORITY (4096)
#endif
#endif // ETHERNET_RX_BUFSIZE_LOW_PRIORITY

#if ETHERNET_RX_HP_QUEUE
#ifndef ETHERNET_RX_BUFSIZE_HIGH_PRIORITY
#define ETHERNET_RX_BUFSIZE_HIGH_PRIORITY (2048)
#endif
#else
#define ETHERNET_RX_BUFSIZE_HIGH_PRIORITY (0)
#endif

#ifndef ETHERNET_TX_BUFSIZE_LOW_PRIORITY
#ifdef ETHERNET_TX_BUFSIZE
#define ETHERNET_TX_BUFSIZE_LOW_PRIORITY ETHERNET_TX_BUFSIZE
#else
#define ETHERNET_TX_BUFSIZE_LOW_PRIORITY (4096)
#endif
#endif // ETHERNET_TX_BUFSIZE_LOW_PRIORITY

#if ETHERNET_TX_HP_QUEUE
#ifndef ETHERNET_TX_BUFSIZE_HIGH_PRIORITY
#define ETHERNET_TX_BUFSIZE_HIGH_PRIORITY (2048)
#endif
#else
#define ETHERNET_TX_BUFSIZE_HIGH_PRIORITY (0)
#endif

#ifndef ENABLE_ETHERNET_PORT_FORWARDING
#define ENABLE_ETHERNET_PORT_FORWARDING (0)
#endif

#define ETHERNET_FILTER_PORT_FORWARD_MASK 0x80000000

#ifndef ETHERNET_RX_CLIENT_QUEUE_SIZE
#define ETHERNET_RX_CLIENT_QUEUE_SIZE (4)
#endif

#ifndef ETHERNET_LITE_RX_BUFSIZE
#define ETHERNET_LITE_RX_BUFSIZE (3200)
#endif

#ifndef ETHERNET_TX_MAX_PACKET_SIZE
#define ETHERNET_TX_MAX_PACKET_SIZE ETHERNET_MAX_PACKET_SIZE
#endif

#ifndef ETHERNET_RX_MAX_PACKET_SIZE
#define ETHERNET_RX_MAX_PACKET_SIZE ETHERNET_MAX_PACKET_SIZE
#endif
