#ifndef __XSCOPE_CONTROL_H__
#define __XSCOPE_CONTROL_H__

#include <xs1.h>
#include <xscope_cmds_enum.h> // Autogenerated. See CMakeLists.txt

void xscope_control(chanend c_xscope, chanend c_clients[num_clients], static const unsigned num_clients);

#endif
